---
- hosts: all
  tasks:
    - lineinfile:
        dest: /etc/hosts
        regexp: '.*127\.0\.0\.1.*{{ inventory_hostname }}'
        state: absent
      become: true
      
    - blockinfile:
        dest: /etc/hosts
        block: "{{ hostvars[item].ansible_host }}    {{ item }}"
        marker: "# {mark} ANSIBLE MANAGED BLOCK {{ item }}"
      with_items: "{{ groups['all'] }}" 
      become: true
