---
- include: install-pkg-check.yaml pkg_name=mesos

- name: add mesosphere repository
  include: install-add-repo.yaml
  when: mesos_install
  become: true

- name: set additional mesos facts
  include: install-facts.yaml

- name: update apt-get repository
  apt: update_cache=yes
  when: not was_pkg_installed

- name: install mesos from repository
  apt: name=mesos
  when: not was_mesos_installed and mesos_install_from_repository
  become: true

- include: install-pkg-deb.yaml pkg_name=mesos
  when: not was_mesos_installed and mesos_install_from_deb