---
- name: check mesos installation
  include: install-check.yaml

- name: add mesosphere repository
  include: install-add-repo.yaml
  when: mesos_install
  become: true

- name: set additional mesos facts
  include: install-facts.yaml

# install from repository without keeping archives
- name: install mesos
  apt: name=mesos update_cache=yes
  when: not was_mesos_installed and mesos_install_from_repository
  become: true

# install from repository but keep archives
- include: install-deb.yaml
  when: not was_mesos_installed and mesos_install_from_deb