---
- include: install.yaml
  when: mesos_install

- include: marathon.yaml
  when: was_mesos_master and mesos_install_marathon

- include: mesos-dns.yaml
  when: was_mesos_agent and mesos_install_mesos_dns

- include: configure.yaml
  when: mesos_install or mesos_configure

- include: start.yaml
  when: mesos_start

- include: stop.yaml
  when: mesos_stop