---
- include: install.yaml
  when: mesos_install

- include: zookeeper.yaml

- include: master.yaml
  when: was_mesos_master
  become: true

- include: agent.yaml
  when: was_mesos_agent
  become: true

