---
- include: install.yaml
  when: mesos_install

- include: configure.yaml
  when: mesos_install or mesos_configure

- include: start.yaml
  when: mesos_start

- include: stop.yaml
  when: mesos_stop