---
# should be moved to zookeeper.yaml
- name: configure mesos-master zookeeper
  template:
    src: "mesos-zk.j2"
    dest: "{{ mesos_zk_path }}"
  tags:
    - configure-master-zk

- name: configure mesos master
  copy: content="{{ item.value }}" dest="{{ mesos_master_config_path }}/{{ item.key }}"
  with_dict: "{{ mesos_master_default_configurations | combine(mesos_master_configurations) }}"
  
- name: stop mesos-agent on master
  service: name=mesos-slave state=stopped

- name: disable mesos-agent on master
  copy: content="manual" dest="{{ mesos_agent_override_path }}"

- name: restart mesos-master service
  service: name=mesos-master state=restarted

- name: restart marathon service
  service: name=marathon state=restarted
  when: mesos_install_marathon