---
- include: spark_home.yaml

- name: download spark-client jar with dependencies
  local_action: get_url
  args:
    url: "{{ spark_alluxio_clientjar_url }}"
    dest: "{{ spark_alluxio_clientjar_path }}"
  run_once: true
  become: true

- name: copy spark-client jar to default spark_classpath
  copy:
    src: "{{ spark_alluxio_clientjar_path }}"
    dest: "{{ spark_home_env }}/jars"
    owner: "{{ spark_user }}"
    group: "{{ spark_group }}"
  become: true

- name: restart spark cluster
  set_fact: spark_restart=true